language: ruby

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  - jruby-head
  - truffleruby

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby

cache: bundler

script: bundle exec rake

notifications:
  disable: true
