language: ruby

rvm:
  - 1.9
  - 2.0
  - 2.1
  - jruby-19mode
  - jruby-head
  - rbx-2

sudo: false

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-head

script: "rake test"

notifications:
  disable: true
