language: ruby

rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - &latest_ruby 2.6
  - ruby-head
  - jruby-head
#  - rbx-2

addons:
  apt:
    packages:
    - libgmp3-dev

matrix:
  include:
    - rvm: *latest_ruby
      script: bundle exec rake memory_profile:run
      name: Profiling Memory Usage
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

install:
  - bundle install

script: bundle exec rake

notifications:
  disable: true
