language: ruby
cache: bundler

rvm:
  - 2.4
  - 2.5
  - &latest_ruby 2.6

matrix:
  include:
    - rvm: *latest_ruby
      script: bundle exec rake memory_profile:run
      name: Profiling Memory Usage

branches:
  only:
    - master
    - gh-pages
    - /.*-stable/

notifications:
  disable: true
